export const columns = [
    { data: "_id", title: "id" },
    { data: 'department', title: 'DEPARTMENT' },
    { data: 'date', title: 'DATE' },
    { data: "board", title: "BOARD", type: 'select', selectOptions: ['BD1', 'BD2', 'BD3', 'BD4', 'BD5'] },
    { data: "section", title: "SECTION" },
    { data: 'avl_start', title: 'AVAILABLE SLOT START TIME' },
    { data: 'avl_end', title: 'AVAILABLE SLOT END TIME' },
    { data: 'stationTo', title: 'STATION TO' },
    { data: 'stationFrom', title: 'STATION FROM' },
    { data: 'direction', title: 'DIRECTION' },
    { data: 'series', title: 'SERIES' },
    { data: "ni", title: "Whether NI work/PNI work or Non-NI Work" },
    { data: "yard", title: "Yard" },
    { data: "lineNo", title: "KM/LINE" },
    { data: "machine", title: "Machine Type & No." },
    { data: "typeOfWork", title: "TYPE OF WORK" },
    { data: "time", title: "BLOCK DEMAND HOURS" },
    { data: "quantum", title: "QUANTUM" },
    { data: "deputedSupervisior", title: "DEPUTED SUPERVISIOR" },
    { data: "resources", title: "RESOURCES" },
    { data: "loco", title: "LOCO" },
    { data: "crew", title: "CREW" },
    { data: "remarks", title: " REMARKS IF ANY" },
    { data: "approval", title: "APPROVAL REQUIRED OR NOT " },
    { data: "s_tStaff", title: "S&T STAFF REQUIRED (YES/NO)" },
    { data: "tpcStaff", title: "TPC STAFF REQUIRED (YES/NO)" },
    { data: "point", title: "POINT/BPAC/OTHERS" },
    { data: "tower", title: "TOWER WAGON/MATERIAL TRAIN" },
];