export const workTypeList =[
    'PQRS WORK',
    'MACHINE TAMPING',
    'M/C PACKING',
    'RAIL CARRYING',
    'CTR WORK',
    'PACKING',
    'MFI WORK',
    'TAMPING WORK',
    'DSMG WORK OF POINT,TRACK, BPAC & SIGNAL',
    'POST BCM',
    'POINT PACKING WORK',
    'CROSS OVER',
    'RAIL LOADING WORK',
    'RAIL UNLOADING WORK',
    'RAIL LOADING & UNLOADING',
    'LOCAL ADJUSTMENT OF CURVE AND ALLIGNMENT',
    'OTHERS'

]